
name: 'retail_supply_chain'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ['models']

models:
  retail_supply_chain:
    staging:
      materialized: view
    marts:
      materialized: table
