default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: your_account_id.region.gcp  # example: abc12345.us-east-1
      user: your_username
      password: your_password
      role: your_role
      database: your_database
      warehouse: your_warehouse
      schema: your_schema
      threads: 1
      client_session_keep_alive: false

